### PR TITLE
Fix/sub company banner

### PR DESCRIPTION
**Pull request by ghislaineguerin**

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ghislaineguerin why are you modifying .gitignore and adding those index files? They're not needed in the repo. Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu it is now ready for review.

**Comment by alex-deaconu** [comment]
:+1: !

**Comment by ghislaineguerin** [comment]
@ezequielc we need to merge this along with your warning message so I can fix the styling properly

**Pull request merged**
