### PR TITLE
Fix/padding utility

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc @fjvallarino 
I had to revert this one and fix a bower resolution + package.json version number.
Please validate, thanks!

**Comment by alex-deaconu** [comment]
@RV-Adrian my suggestion is to set the version to `1.12.1` since `1.12.0` will need to be replaced. Thanks.

**Comment by alex-deaconu** [comment]
@RV-Adrian you missed one file to bump. Fixed with another commit, so we should be good to go. 👍

**Comment by RV-Adrian** [comment]
@alex-deaconu Thanks! Deploying now 👍

**Pull request merged**
