### PR TITLE
Feature/purchase flow css cleanup

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu 
Just a reorganization of some CSS classes here, as per chat with @ghislaineguerin 
The only thing removed is -input[type=radio] , since it's a minor-impact overwrite, and we're trying to reduce bloat overall. BEM stuff to come later on. Thx!

**Comment by alex-deaconu** [comment]
@RV-Adrian sounds good. @ghislaineguerin can you please review? Thanks.

**Comment by ghislaineguerin** [comment]
@RV-Adrian looks good.

**Comment by RV-Adrian** [comment]
@ghislaineguerin Thanks
@alex-deaconu Good to go

**Comment by alex-deaconu** [comment]
@ghislaineguerin @RV-Adrian thanks!

**Pull request merged**
