### PR TITLE
add linker to referral

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu @ezequielc 
this is the code we need to add to segment script. Let me know if this looks ok.

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ghislaineguerin unit tests need to be fixed for this. I can do so after the functionality has been validated by @ezequielc (I don't know what I should be looking for). Thanks!

**Comment by ezequielc** [comment]
@ghislaineguerin @alex-deaconu It seems to be working as expected 👍  Don't forget to bump version. Thanks!

**Comment by ghislaineguerin** [comment]
@ezequielc great! thanks. @alex-deaconu are you going to merge this?

**Comment by alex-deaconu** [comment]
@ghislaineguerin yes I'll work on this next. Should be out by this afternoon. Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc @fjvallarino I just added a simple unit test and bumped the version. Staged on stage-2. Please review. Thanks!

**Pull request merged**
