### PR TITLE
Update angular to 1.5.9; fix common-i18n issue

### PR DESCRIPTION
**Pull request by alex-deaconu**

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Using Angular 1.6.0 is throwing a lot of errors in the Unit Tests: `Possibly unhandled rejection`
https://circleci.com/gh/Rise-Vision/common-header/1331

Using Angular 1.5.9 instead.

Also updated the common-i18n version and fixed some dependencies.

@Rise-Vision/apps please review. Thanks!

**Comment by fjvallarino** [comment]
@alex-deaconu one option is explicitely ignoring that error: https://github.com/angular-ui/ui-router/issues/2889#issuecomment-257654153

**Comment by alex-deaconu** [comment]
@fjvallarino yes I saw that reply as well. Tried it out:
```
app.config(['$qProvider', function ($qProvider) {
    $qProvider.errorOnUnhandledRejections(false);
}]);
```
and it resolves the unit test errors and the errors shown in Apps. There is one Apps unit test that fails related to the i18n library, which can most likely be fixed.

However, my thinking is that since Angular 1.6.0 is quite fresh, and it is causing some backwards compatibility issues, maybe we can hold off upgrading as of yet.

@ezequielc FYI.

Thoughts? Thanks.

**Comment by fjvallarino** [comment]
@alex-deaconu agreed

**Comment by alex-deaconu** [comment]
One further fix for this PR. After 1.4 the `ngModel.$parsers` behaviour has changed slightly. Due to this, the `integer-parser` directive was no longer working correctly. Fixed by applying the recommended implementation from the documentation: https://docs.angularjs.org/api/ng/directive/select
(see bottom section: "Binding select to a non-string value via ngModel parsing / formatting") with a few tweaks.

The Directive is used in the Timeline component, Display Settings (Timezone field) and Company Settings (Timezone field).

Staged at https://apps-stage-4.risevision.com

@Rise-Vision/apps please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu 👍

**Comment by alex-deaconu** [comment]
@olegrise FYI this is the update I was talking about at SoS. Thanks.

**Comment by olegrise** [comment]
Thank you @alex-deaconu. I created a card on the Store board to upgrade to the 1.5.9.

**Comment by alex-deaconu** [comment]
@olegrise sounds good. Merging this for now; we can resolve any Store specific issues when working on that card. Thanks!

**Comment by olegrise** [comment]
@alex-deaconu sounds good.

**Pull request merged**
