### PR TITLE
Updated Sign-up modal wording and styles

### PR DESCRIPTION
**Pull request by alex-deaconu**
Requires new common-style version

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@olegrise @rodrigopavezi please review. 

@ghislaineguerin do you want me to stage this somewhere for you to review?

Thanks.

**Comment by olegrise** [comment]
:+1:

**Comment by ghislaineguerin** [comment]
@alex-deaconu Yes, please. I totally missed that, sorry.

**Comment by rodrigopavezi** [comment]
LG :+1:

**Pull request merged**
