### PR TITLE
Use Store's DB status name 'Trial' instead of 'On Trial' from Subscription Service

### PR DESCRIPTION
**Pull request by fjvallarino**
@Rise-Vision/apps @rudibravo please review

### CODE REVIEW

**Comment by rudibravo** [comment]
@fjvallarino 👍

**Comment by alex-deaconu** [comment]
@fjvallarino @rudibravo would there be any reason to support both versions of the string? Thanks.

**Comment by fjvallarino** [comment]
@alex-deaconu this only affects the CompanySubscriptions object. "Trial" is the value as stored in Store's DB, "On Trial" is how Subscription Status service returns it. We discussed this today on HipChat (Apps room, around 2pm your time). I'm fine either way.

**Comment by alex-deaconu** [comment]
@fjvallarino okay, I saw the conversation, but was just curious. 👍 Thanks.

**Pull request merged**
