### PR TITLE
Redirect to new URLs in Apps Dropdown

### PR DESCRIPTION
**Pull request by alex-deaconu**
Squashed @RV-Adrian 's branch and fixed an issue with .gitignore.

@ezequielc please review. Thanks.

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc 
Removed some inline CSS as well. Looks like `dist/index.html` got a little strange, even though very little was changed. https://apps-stage-1.risevision.com/ looks alright but let me know if a fix is needed. Thanks!

**Comment by alex-deaconu** [comment]
@RV-Adrian got it. That particular `index.html` file in dist should not be committed. I will fix by adding to `.gitignore`. Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc this PR is ready for review. Thanks.

**Comment by alex-deaconu** [comment]
There was an issue with the links themselves. Fixed by removing the trailing `/`.

**Comment by ezequielc** [comment]
@alex-deaconu :+1:

**Pull request merged**
