### PR TITLE
Add border to users list

### PR DESCRIPTION
**Pull request by alex-deaconu**
Update search to use component
Upgrade Angular to v1.5.11

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Fix for https://github.com/Rise-Vision/rise-vision-apps/issues/336.

Refactored the search component for the User list as well. Also includes an Angular JS update.

Staged at https://apps-stage-0.risevision.com/

@ezequielc @fjvallarino wondering if you can review the code.
@RV-Adrian wondering if you can review the CSS classes I used.

Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu Looks good 👍 
Thanks

**Comment by ezequielc** [comment]
@alex-deaconu Code looks good. Thanks

**Comment by alex-deaconu** [comment]
@olegrise FYI merging this change to CH. It fixes an issue with the Users list, but also upgrades the Angular JS version to 1.5.11. Thanks!

**Comment by olegrise** [comment]
@alex-deaconu thanks.

**Pull request merged**
