### PR TITLE
Collect industry

### PR DESCRIPTION
**Pull request by olegrise**
@Rise-Vision/apps please review

### CODE REVIEW

**Comment by olegrise** [comment]
staged at https://apps-stage-2.risevision.com

**Comment by alex-deaconu** [comment]
@jasoncaldwell to confirm, this is the PR I was referring to.

It is staged at https://apps-stage-2.risevision.com.

Changes involved are the ones defined for the New User flows, as well as existing Users that have not yet picked an Industry for their Organization.

Thanks!

**Comment by alex-deaconu** [comment]
@olegrise PR looks good, thanks for the changes!

**Comment by jasoncaldwell** [comment]
> @jasoncaldwell to confirm, this is the PR I was referring to.
> 
> It is staged at https://apps-stage-2.risevision.com.
> 
> Changes involved are the ones defined for the New User flows, as well as existing Users that have not yet picked an Industry for their Organization.
> 
> Thanks!

@alex-deaconu Looking good! There's a few visual discrepancies that I think need to be addressed. Please see below. If you had any questions, let me know. Thanks!

differences

**Comment by alex-deaconu** [comment]
@jasoncaldwell thanks for the feedback. I will make the wording changes, but in terms of styling those are form specific styles from our style guide. I will take a look if I implemented it incorrectly, but otherwise I think will need to revise the CSS for the whole app. Thoughts? Thanks.

**Comment by alex-deaconu** [comment]
@jasoncaldwell actually it looks like there were some extra classes there interfering. Can you review this and let me know if the styling is as per the prototype? Thanks!
Screen Shot 2019-03-28 at 11 04 43 AM

**Comment by alex-deaconu** [comment]
@jasoncaldwell please review the last commit. I updated the wording and removed the custom styling for that modal (and some extra dead CSS). Thanks!

**Comment by jasoncaldwell** [comment]
> @jasoncaldwell actually it looks like there were some extra classes there interfering. Can you review this and let me know if the styling is as per the prototype? Thanks!
> 
> Screen Shot 2019-03-28 at 11 04 43 AM

@alex-deaconu Looking good! A few other discrepancies ... 

1. Let's remove the close icon on the modal. This modal needs to be mandatory, as per the JTBDs.
2. Watch the vertical grid for the checkbox section.

Other than that, it's looking good. :)

differences2

**Comment by alex-deaconu** [comment]
@jasoncaldwell to confirm, with the removal of the `x` (close button), we also want to prevent the user from closing via the Escape key and via closing outside the dialog? Same behaviour as defined for the Existing User Industry Collection modal? Thanks!

**Comment by jasoncaldwell** [comment]
> @jasoncaldwell to confirm, with the removal of the `x` (close button), we also want to prevent the user from closing via the Escape key and via closing outside the dialog? Same behaviour as defined for the Existing User Industry Collection modal? Thanks!

@alex-deaconu Correct, as I understand it we want to prevent the user from closing the modal via the Escape key as well. cc @ezequielc

**Comment by ezequielc** [comment]
@alex-deaconu @jasoncaldwell I agree on the Close button, we can follow the Industry Collection modal. But if delays the release, we can do it in a separate PR.

@alex-deaconu I found one issue in my tests. If I set the Organization name, it does not get updated in CH on the next screen, only after I reload the page I see the name that I had added. Thanks

**Comment by alex-deaconu** [comment]
@ezequielc thanks for the feedback. I will try to resolve the Organization naming issue. Thanks!

**Comment by alex-deaconu** [comment]
@jasoncaldwell I removed the ability to close the modal, and hopefully resolved the spacing issues.

Wondering if you could review the latest:

Screen Shot 2019-03-28 at 12 49 06 PM

**Comment by alex-deaconu** [comment]
@ezequielc I've updated the branch to fix the issue you described with the Company Name. However, this happens asynchronously after the registration is completed and the modal disappears, so the old name shows up for a few seconds. Wondering if this behaviour is ok or I need to correct it?

Re-staging now...

Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Looks good 👍

**Pull request merged**
