### PR TITLE
Changed check for redirectToRoot option.

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alex-deaconu could you please review? What do you think? This fixed the issue with store so we don't need to move CH to the index.html cheers

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi looks good. @olegrise any objections? Thanks.

**Comment by olegrise** [comment]
Looks good.

**Comment by rodrigopavezi** [comment]
@alex-deaconu is there okay with you if I merge it now and create a new version? cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi something's weird with your PR, more specifically the second commit. Can you squash and rebase so we can only see the first commit's changes? Thanks.

**Pull request closed without merging**
