### PR TITLE
Persist shipToAttention field.

### PR DESCRIPTION
**Pull request by olegrise**
Do not merge. Need to fix tests first.

### CODE REVIEW

**Comment by olegrise** [comment]
@rodrigopavezi please review. This changes are needed for the Store Persist Address tasks. I'm still working on unit tests. I will add them to this PR shortly.
@alex-deaconu FYI.

**Comment by rodrigopavezi** [comment]
@olegrise looks good!

**Comment by rodrigopavezi** [comment]
@olegrise tests are good! :+1:

**Comment by olegrise** [comment]
@rodrigopavezi added unit test. Also fixed "should clear cart" unit test.

**Comment by olegrise** [comment]
Thanks @rodrigopavezi !

**Comment by alex-deaconu** [comment]
:+1:

**Comment by olegrise** [comment]
Thanks @alex-deaconu !

**Pull request merged**
