### PR TITLE
Changes to common-svg & build fix

### PR DESCRIPTION
**Pull request by alex-deaconu**
Remove JSONEdit and jquery.ui dependencies

Increment major version to highlight deps changes

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Build was failing due to https://github.com/bringking/JSONedit.git no longer being available. However, removing this dependency caused jquery-ui and jquery-ui-sortable to no longer be loaded. Hence, they are missing in dependencies.js (I also removed them from gulpfile.js).

Both CH and Apps e2e tests pass without these deps. Also, from my testing on https://apps-stage-4.risevision.com/ where this change is staged, nothing is broken/missing.

@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Code looks good 👍 
@olegrise FYI. Let us know if you think this would affect Store. Thanks!

**Comment by olegrise** [comment]
@alex-deaconu looks good. Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc @olegrise thanks!

**Pull request merged**
