### PR TITLE
[chore] Removing last modified directive

### PR DESCRIPTION
**Pull request by alex-deaconu**
Using common-app-components version instead

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Not sure why `dependencies.js` has so many changes. Did a fresh `bower install`, and this was the result.

@olegrise please review. Thanks!

**Comment by olegrise** [comment]
@alex-deaconu it's better to use `npm run dev` instead of `bower install` in CH.

**Comment by alex-deaconu** [comment]
@olegrise tried that as well, it didn't make a difference in the build results. 

I can just remove `dependencies.js` from this commit, if needed. Thanks.

**Comment by olegrise** [comment]
It looks like CH builds became very unstable recently...

**Comment by olegrise** [comment]
:+1:

**Comment by alex-deaconu** [comment]
I know, I'm trying to figure out a way to fix them. I've tried increasing the timeout but that didn't seem to help. Going to try to pursue other options.

**Pull request merged**
