### PR TITLE
Use animations for Password Change dialog

### PR DESCRIPTION
**Pull request by fjvallarino**
@Rise-Vision/apps please review (deployed to stage-4)

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@fjvallarino code itself looks good, but the animation for the password fields looks really weird. Not sure if it's an improvement over the previous version. @ezequielc thoughts? Thanks.

**Comment by ezequielc** [comment]
@fjvallarino I agree with @alex-deaconu. The 'up' animation doesn't look great. I am wondering if you can apply 'fadeIn' class instead of 'fadeInUp'. Maybe it will require @RV-Adrian help. Thanks

**Comment by RV-Adrian** [comment]
@fjvallarino @alex-deaconu @ezequielc 
I agree it's jarring. Initially, that was the intent since the Password form fields had 'appeared' without notice when using a standard fade. 
I can look into other animation properties, or add some other visual queue if it can wait for Monday.

**Comment by ezequielc** [comment]
@RV-Adrian Yes, it can wait. We can release without it and update later. Thanks

**Pull request closed without merging**
