### PR TITLE
Onboarding slider styling

### PR DESCRIPTION
**Pull request by alex-deaconu**
@ghislaineguerin @RV-Adrian please review. Thanks!

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @ghislaineguerin 
Looks good to me 👍 

@ghislaineguerin Curious what prompted the update to $rise-green? Any further actions that should come from this change to have consistency?

**Comment by alex-deaconu** [comment]
@RV-Adrian good question! I see the same (updated) colour being used in the Website as well. Was this a branding change that we are supposed to replicate everywhere?

@ghislaineguerin @ezequielc any ideas? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu @RV-Adrian I am not aware of requested changes. @ghislaineguerin Any feedback? Thanks

**Comment by alex-deaconu** [comment]
@Rise-Vision/apps removed the colour changes as discussed, and restaged at stage-3. Please review. Thanks!

**Pull request merged**
