### PR TITLE
Fix/container testing

### PR DESCRIPTION
**Pull request by RV-Adrian**
@ezequielc @alex-deaconu @fjvallarino 
Release tag PR as discussed. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@RV-Adrian my suggestion is that when creating a PR for the common-header, you don't include the dependencies.js/dependencies.min.js files in the commit. In this case you're inadvertently updating the Angular js version, which could cause undesired effects. 

Also, the common-header build includes common-app-components dist files. Those are missing in this PR. Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu 
Dependencies reverted. 'gulp build' didn't create any diffed common-header*.js files it seems.

**Comment by alex-deaconu** [comment]
@RV-Adrian interesting, I guess those files are not included in the build. Since this PR only updates the common-style version, I would suggest we just close it. We can update the version tag in the following PR you have open. Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu Agreed. Thx!

**Pull request closed without merging**
