### PR TITLE
Replace $log.x calls to console.x in order to have Fullstory capture logging statements

### PR DESCRIPTION
**Pull request by fjvallarino**
@Rise-Vision/apps @olegrise please review

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@fjvallarino curious, were there Dependencies updated in dependencies.js? And what were those updates? I can't see the diff in github it says it's too large. Thanks.

**Comment by olegrise** [comment]
@fjvallarino some changes in dist/js/common-header.js don't make sense. It looks like you have outdated version of common-app-components on your PC. Try running `bower update` first and then re-build CH.

**Comment by fjvallarino** [comment]
@alex-deaconu I had replaced the $log calls in the dist files manually, those were the updates. I just built and bumped the version, so it should be fine now.

@olegrise updated!

**Comment by olegrise** [comment]
@fjvallarino looks good now.

**Comment by alex-deaconu** [comment]
@fjvallarino 👍

**Pull request merged**
