### PR TITLE
Moved segment-analytics service to common-app-components

### PR DESCRIPTION
**Pull request by alex-deaconu**
Updated to angular 1.3.17.

Please note this is a breaking change for analytics code. The `risevision.common.analytics` module is no longer available, you should use `risevision.common.components.analytics` instead. Will create `v1.4.0` to reflect this.

@olegrise @rodrigopavezi please review. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Build is failing due to this PR not yet being merged: https://github.com/Rise-Vision/common-app-components/pull/19. Thanks.

**Comment by alex-deaconu** [comment]
Fixed.

**Comment by olegrise** [comment]
@alex-deaconu looks good. I will create a Trello card to upgrade to CH 1.4

**Comment by alex-deaconu** [comment]
@olegrise sounds good. Thanks!

**Pull request merged**
