### PR TITLE
Add validation for CC fields

### PR DESCRIPTION
**Pull request by alex-deaconu**
CC Address validation and checkbox

Fix form submits
Further cleanup

Stub CC server side validation

Alpha Release:
Hide On Account & Existing CC selectors

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Final UI look for the Alpha release of the Payment Methods form. Basically, we're only allowing a New CC to be entered (no existing cards or invoice me options).

Fixed some other issues I found with the checkout (pressing Enter while on a field would navigate Backwards).

Also, using `ng-if`s for hiding/showing form components; from my testing this doesn't break anything.

@Rise-Vision/apps please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Looks good. Could you make 'Same as billing address' be checked by default? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc good point, I wasn't 100% sure about that and forgot to confirm. Updated and restaged. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Looks good. Thanks!

**Comment by fjvallarino** [comment]
@alex-deaconu looks good 👍

**Pull request merged**
