### PR TITLE
Do not allow requesting password reset for Google accounts

### PR DESCRIPTION
**Pull request by fjvallarino**
@Rise-Vision/apps please review. This is ready for review at https://apps-stage-2.risevision.com

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@fjvallarino are the dependencies.js changes intentional?

**Comment by fjvallarino** [comment]
@alex-deaconu I cloned common-header from scratch. Maybe some dependencies were old and by building from zero they got updated?

**Comment by alex-deaconu** [comment]
@fjvallarino not sure. From what I see it's ui-router that's changed. However, looks like the version is actually reverted:

```
- * @version v0.2.18
+ * @version v0.2.15
```

**Comment by alex-deaconu** [comment]
@fjvallarino looks good 👍 . Just a reminder to bump versions one more time. Thanks.

**Pull request merged**
