### PR TITLE
Add `url` property to segment.track()

### PR DESCRIPTION
**Pull request by olegrise**
We need a way to tell if `track` event was triggered on production or other environment.

@alex-deaconu please review. @rodrigopavezi FYI.

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@olegrise looks good :+1: . 

Wondering if you can update the unit tests to reflect this change? Thanks!

**Comment by olegrise** [comment]
@alex-deaconu I can't figure out how to test it. I was trying to use `analytics.on('track',...)` as described [here](https://segment.com/docs/libraries/analytics.js/#emitter) - it's not working, then I was trying to use a [callback property](https://segment.com/docs/libraries/analytics.js/#track) - same story - callback is not fired. My next best idea is to add a `_track` wrapper method to the `analyticsEvents`. What do you think?

**Comment by alex-deaconu** [comment]
@olegrise interesting. I'm wondering if you can mock the `$window.analytics` object and go from there. Thanks.

**Comment by olegrise** [comment]
@alex-deaconu I tried that. Same story.

**Comment by olegrise** [comment]
@alex-deaconu interesting idea. That might work. Thanks for the suggestions.

**Comment by olegrise** [comment]
@alex-deaconu added test - see the last commit. Thanks.

**Comment by alex-deaconu** [comment]
@olegrise build failing because of jshint error: analytics is not defined. 

Otherwise, test looks good. Thanks for adding.

**Comment by olegrise** [comment]
@alex-deaconu oh-oh. Fixed it. Sorry about that.

**Comment by alex-deaconu** [comment]
Nice, I like how simple this turned out. Great job!

**Comment by rodrigopavezi** [comment]
@olegrise awesome!!

**Pull request merged**
