### PR TITLE
Fix initial value on User Active State

### PR DESCRIPTION
**Pull request by ezequielc**
Fix for Issue #301. I reviewed and didn't find any other `select` tags that could have the same issue.
@Rise-Vision/apps Please review. Thanks

### CODE REVIEW

**Comment by fjvallarino** [comment]
:+1:

**Comment by alex-deaconu** [comment]
👍

**Comment by alex-deaconu** [comment]
@olegrise FYI you may want to update Store CH version with this fix as well. Thanks.

**Comment by olegrise** [comment]
Thanks @alex-deaconu. I created a card for that.

**Pull request merged**
