### PR TITLE
css review fixes

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu here are the fixes to the css review doc list of issues.
https://docs.google.com/document/d/11KpkYuYIJM5yFRnIeLDb9YQEYRZXYUCbqtP022HNrog/edit

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@alex-deaconu I have pushed a new version that fixes the issues you mentioned on hipchat.

**Comment by alex-deaconu** [comment]
@ghislaineguerin thanks for fixing! Looks good to me 👍 

@ezequielc this is staged at https://apps-stage-1.risevision.com/ if you want to take a quick look.

Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc it did get overwritten... Re-staged to https://apps-stage-2.risevision.com. Sorry about that. Thanks.

**Comment by ezequielc** [comment]
@ghislaineguerin @alex-deaconu Looks good.
The "Secure Checkout from ChargeBee and ..." seems a bit big, but maybe because I was used to the previous version. Thanks!

**Pull request merged**
