### PR TITLE
[feature] Show email and company name

### PR DESCRIPTION
**Pull request by alex-deaconu**
Updated app nav icons to use SVG

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@olegrise this is the first part for the UX review changes for the CH. Second part which includes an updated User/Company menu is still being discussed.

Please review. Thanks!

**Comment by ByronDarlison** [comment]
@ghislaineguerin how is the revised company selector stuff coming? Thanks

**Comment by ghislaineguerin** [comment]
@ByronDarlison adding final details for the mobile view. I will post in about 20 min

**Comment by olegrise** [comment]
:+1:

**Pull request merged**
