### PR TITLE
Fix style guide issues

### PR DESCRIPTION
**Pull request by andrecardoso**
## Description
Fix defects related to style guide mismatching: 

- https://github.com/Rise-Vision/rise-vision-apps/issues/1068
- https://github.com/Rise-Vision/rise-vision-apps/issues/1069
- https://github.com/Rise-Vision/rise-vision-apps/issues/1070
- Everything in [this document](https://docs.google.com/document/d/13hSHSo8FMMo9CXDo4lutGRXcLCwCTGefOC-EXPTMhog/edit?ts=5d3634cb) except modals 

## Motivation and Context

Current UI doesn't match with the style guide

## How Has This Been Tested?

Changes are deployed to [stage-3](https://apps-stage-3.risevision.com/editor/list?cid=b258739a-527b-438c-b6ec-01057cecdfa2). I tested on both desktop and mobile using browserstack.

## Release Plan:
**Automated Test** No need to update, as it was only a style change
**Monitoring** Will validate the release once in Production
**Rollback** Rollback can be done by reverting the PR and following the deployment process
**Documentation**  No need to update documentation
**Internal Communication** I will post a message on slack regarding these changes

- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

### CODE REVIEW

**Comment by andrecardoso** [comment]
[(3) [Issue #1068] rise-data-financial does not follow the style guide](https://trello.com/c/pbsf4QaQ/184-3-issue-1068-rise-data-financial-does-not-follow-the-style-guide)

**Comment by andrecardoso** [comment]
[(3) [Issue #1069] Template editor header does not match style guide](https://trello.com/c/jKZK8Eli/185-3-issue-1069-template-editor-header-does-not-match-style-guide)

**Comment by andrecardoso** [comment]
[(3) [Issue #1070] Component list in template editor does not match style guide](https://trello.com/c/rFHHVsTv/191-3-issue-1070-component-list-in-template-editor-does-not-match-style-guide)

**Comment by olegrise** [comment]
@andrecardoso you had a question about box shadow in the Template Editor UI Review doc. I think @jasoncaldwell meant this 
Screen Shot 2019-07-26 at 2 37 11 PM

**Comment by andrecardoso** [comment]
@olegrise makes sense. I changed it in my last commit. Thanks!

**Comment by andrecardoso** [comment]
[(2) Merge/deploy UI style guide fixes](https://trello.com/c/nZ6KTJ2z/193-2-merge-deploy-ui-style-guide-fixes)

**Pull request merged**
