### PR TITLE
Optional 'link-cid' directive for CH links

### PR DESCRIPTION
**Pull request by alex-deaconu**
@ezequielc please review. 

@olegrise FYI this feature is being added to CH in case Store needs it.

Thanks.

### CODE REVIEW

**Comment by ezequielc** [comment]
@alex-deaconu Looks good :+1: Thanks

**Comment by olegrise** [comment]
@alex-deaconu aah, cool! Where is the implementation of the "link-cid" directive?

**Comment by alex-deaconu** [comment]
@olegrise `link-cid` is included with the CH build: https://github.com/Rise-Vision/common-header/blob/master/src/js/directives/dtv-link-cid.js. Thanks.

**Comment by olegrise** [comment]
@alex-deaconu thanks!

**Pull request merged**
