### PR TITLE
[fix] Updating province code

### PR DESCRIPTION
**Pull request by alex-deaconu**
@olegrise please review. Thanks!

### CODE REVIEW

**Comment by brianloosbrock** [comment]
@olegrise Instead of changing the Nunavut province code in Store should we just update to this version of CH to use this fix? Thanks

**Comment by olegrise** [comment]
:+1:

**Comment by olegrise** [comment]
@brianloosbrock Good idea. I'll stage it first to make sure there are no surprises.

**Comment by olegrise** [comment]
@brianloosbrock Store that uses new CH is staged at https://store-stage-1.risevision.com

**Pull request merged**
