### PR TITLE
Added some sleeps after login

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alex-deaconu please review. cheers

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi I'm going to re-build a couple of times to verify. Thanks.

**Comment by alex-deaconu** [comment]
@rodrigopavezi works like a charm! :+1: . Thanks for fixing.

**Comment by rodrigopavezi** [comment]
@alex-deaconu /Fingers-Crossed

**Comment by rodrigopavezi** [comment]
@alex-deaconu awesome, thanks!

**Pull request merged**
