### PR TITLE
Update settings of the User Company 

### PR DESCRIPTION
**Pull request by olegrise**
- add `updateUserCompanySettings` method
- add `noFollow` parameter to `getCopyOfUserCompany` and `getCopyOfSelectedCompany`
- add `"companyId"` parameter to `$rootScope.$broadcast("risevision.company.updated",...`.

@alex-deaconu please review

### CODE REVIEW

**Comment by olegrise** [comment]
@rodrigopavezi, sorry forgot to add you to this PR. Please review. 

The problem Store currently faces is following:
1) Store gets a copy of the selected company by calling `userState.getCopyOfSelectedCompany();`. 
2) User edits company address and clicks Save button.
3) Store needs to update fields of the company object which belongs to CH companyState.  There is a method for that called  `userState.updateCompanySettings()`.  The problem is that when `userState.updateCompanySettings()` is called, it looses all object fields except address fields that were updated. I believe the reason for this is the way `getCopyOfSelectedCompany` wraps up an object.

**Comment by rodrigopavezi** [comment]
@olegrise looks good. It is just missing tests. cheers

**Comment by olegrise** [comment]
@rodrigopavezi added tests. Please review.

**Comment by rodrigopavezi** [comment]
@olegrise looks good!! :+1:

**Comment by alex-deaconu** [comment]
@olegrise @rodrigopavezi I don't see why we needed to add a second function for this. Why not:
```
        updateCompanySettings: function (company) {
          if (company && company.id === _state.getSelectedCompanyId()) {
            objectHelper.clearAndCopy(company, _state.selectedCompany);
          }
          if (company && company.id === _state.getUserCompanyId()) {
            objectHelper.clearAndCopy(company, _state.userCompany);
          }

          $rootScope.$broadcast("risevision.company.updated", {
            "companyId": company.id
          });
        },
```

**Comment by olegrise** [comment]
@alex-deaconu Good point. I don't see any problems with one function.

**Pull request merged**
