### PR TITLE
Fix/adds omitted files for video's muted in preview message

### PR DESCRIPTION
**Pull request by jungeunyoon**
- omitted `dist/locales/translation_en.json` file from #812

### CODE REVIEW

**Comment by jungeunyoon** [comment]
[widget-video -- Issue 213 [3]](https://trello.com/c/fhriNHQ7/5324-widget-video-issue-213-3)

**Comment by alex-deaconu** [comment]
@jungeunyoon most likely yes.

**Comment by jungeunyoon** [comment]
@alex-deaconu any insight into how to manually trigger one without reopening a PR?

**Comment by alex-deaconu** [comment]
@jungeunyoon I doubt reopening the PR will trigger it. The triggers are active, just CCI is not responding to them.

Also to note, when the common-header builds start working, make sure only one runs. It doesn't really like builds in parallel.

Thanks.

**Comment by jungeunyoon** [comment]
@alex-deaconu oh wow those suddenly went off. hmm thanks!

**Comment by alex-deaconu** [comment]
@jungeunyoon ya, it didn't find the commits however due to the force push. Your build should come along shortly 👍

**Pull request merged**
