### PR TITLE
Deprecate unused components to reduce requests

### PR DESCRIPTION
**Pull request by alex-deaconu**
Remove shopping cart, system messages
Remove subscription status check for priority support

### CODE REVIEW

**Comment by olegrise** [comment]
@alex-deaconu not sure if we should remove the shopping cart. Store is not fully deprecated yet. We might not be able re-build it using the latest CH versions. What do you think?

**Comment by alex-deaconu** [comment]
@olegrise my plan is to update Store to reflect these changes. Thoughts? Thanks.

**Comment by olegrise** [comment]
@alex-deaconu that works. Thanks.

**Comment by alex-deaconu** [comment]
Screen Shot 2019-04-16 at 4 16 44 PM

Staged at:
https://apps-stage-1.risevision.com
https://store-stage-0.risevision.com

@Rise-Vision/apps please review. Thanks!

**Pull request merged**
