### PR TITLE
Fix/store link

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc @fjvallarino 
Please review fix for https://trello.com/c/KMZqqVQm/2208-common-header-store-account-link-not-styled-correctly-on-small-resolutions-1

**Comment by alex-deaconu** [comment]
@RV-Adrian double checked staging and this is what I saw: 
screen shot 2017-04-18 at 2 58 15 pm

**Comment by ezequielc** [comment]
@alex-deaconu @RV-Adrian Fix works fine for me. Thanks
screen shot 2017-04-18 at 9 13 53 pm

**Comment by RV-Adrian** [comment]
@alex-deaconu It looks like it's sticking to the top of the browser window?
If so, couldn't recreate that via Chrome.

**Comment by alex-deaconu** [comment]
@ezequielc @RV-Adrian here's a more in depth description of what I'm seeing: https://screencast.com/t/SYtZNkbPvt5. Not sure if it's an issue we need to address now or not. Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu Got it, thanks. The two may be somewhat related. I'll take a look.

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc 
PS - Both those issues are as-deployed currently, so maybe another point card would be ideal.

**Comment by ezequielc** [comment]
@RV-Adrian @alex-deaconu I agree, we can handle them separately. @RV-Adrian Could you add a card in our backlog? Thanks

**Comment by alex-deaconu** [comment]
@RV-Adrian @ezequielc agreed re: fixing as a separate card. Should have checked existing version first before bringing this up; my bad.

**Comment by RV-Adrian** [comment]
@alex-deaconu 
Looks like this is good to go, thanks for the heads-up.

**Comment by alex-deaconu** [comment]
@RV-Adrian 👍

**Pull request merged**
