### PR TITLE
fix scrolling list

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu this is the fix for the scrolling list

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Staged at https://apps-stage-4.risevision.com

@ezequielc @RV-Adrian please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc @RV-Adrian as discussed in standup, the selector on stage-4 won't have the fix. However you can use the URL directly:
https://apps-stage-4.risevision.com/storage-selector.html#/?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443&selector-type=single-file.

The fix works for me. Let me know if you can confirm, or I should re-stage to stage-0. Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu 👍 Works!

**Comment by ezequielc** [comment]
@alex-deaconu 👍

**Pull request merged**
