### PR TITLE
Add classes for kissmetrics form tracking

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@olegrise Please review.
I need these classes to track form events on kissmetrics. Thanks.

### CODE REVIEW

**Comment by olegrise** [comment]
@ghislaineguerin looks good. The only thing is that when you make a change to CH, you need to build it in order to generate distribution files and then include them in PR. The command for that is `NODE_ENV=prod gulp build`. I just added missing dist files to this PR and squshed.
@alex-deaconu FYI.

**Comment by ghislaineguerin** [comment]
@alex-deaconu could you review this please? I have added ID and name attributes for tracking.

**Comment by alex-deaconu** [comment]
@ghislaineguerin something is weird in your build results. `src/html/popup-auth_e2e.html` should not be changed in this PR. 

Otherwise looks good :+1: . Thanks.

**Comment by alex-deaconu** [comment]
@ghislaineguerin fixed the build results and squashed. @olegrise FYI. Thanks.

**Pull request merged**
