### PR TITLE
Fix/update fields

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu Please review
https://apps-stage-4.risevision.com/

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ghislaineguerin 👍

**Comment by ghislaineguerin** [comment]
@fjvallarino please review.

**Comment by fjvallarino** [comment]
@ghislaineguerin looks good! Can you merge master into this branch, and bump versions? I'll approve after that

**Comment by ghislaineguerin** [comment]
@fjvallarino do I still need approval here? it's not letting me merge

**Pull request merged**
