### PR TITLE
Quick fix for multiple accounts

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu Please review. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc your CH dependencies are out of date. The PR actually decrements the Angular version from .18 to .15. Can you please double check your local env and rebuild? Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc 👍

**Comment by ezequielc** [comment]
@alex-deaconu We should update RVA and Store too. Anything else?
@olegrise fyi

**Comment by alex-deaconu** [comment]
@ezequielc I believe developer.risevision.com is using CH as well. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Sounds good. Will update it too. Thanks

**Comment by olegrise** [comment]
@alex-deaconu Sounds good. Created PR https://github.com/Rise-Vision/store/pull/1214.

**Pull request merged**
