### PR TITLE
Checkout form UI implementation

### PR DESCRIPTION
**Pull request by alex-deaconu**
Clean out Checkout fields
Angular logic for dropdowns

Clean out unneeded partials

### CODE REVIEW

**Comment by alex-deaconu** [comment]
This is the basic UI implementation of the Payment Methods page, as well as the Credit Card fields.

To confirm, after going through the Product Selection and Address Steps (you can skip some validation steps for addresses if you enter a non CA/US address), you will see the Payment Methods form.

From there you can select the various options. I've pre-filled some sample credit cards for staging purposes. To note, the CC Address implementation, as well as form validation are still not implemented.

@Rise-Vision/apps please review. Thanks!

**Comment by olegrise** [comment]
@alex-deaconu couple of observations:
- What's the benefit of showing the Security Code for the existing card? Should we hide it?
- It's not related to this PR - I've noticed that "Same As Billing Address" checkbox is missing on the Shipping Address page. Did we scope it out of this release? If not, we might consider doing that for both Shipping Address and Payment pages if it saves us some time.
@ezequielc

**Comment by alex-deaconu** [comment]
@olegrise 

- I agree. I just had it there because it was in the prototype.
- Re. "Same as Billing Address" I'm not sure what happened to that checkbox; somewhere along the way we scoped it out (it's currently commented in the code: https://github.com/Rise-Vision/common-header/pull/838/files#diff-c40e6d49cf4cef80bd65b1e55ba2901cR11). @ezequielc do you recall that conversation/reason for it?

Thanks.

**Comment by olegrise** [comment]
@alex-deaconu everything looks good. The only remaining question is if we should hide Security Code. Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc @fjvallarino updated the PR to re-name "Generate Invoice" to "Invoice Me" and remove the Security Code field from the Existing CC form.

Re-staged at https://apps-stage-3.risevision.com.

This is ready for final review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu Looks good. Thanks

**Comment by fjvallarino** [comment]
@alex-deaconu looks good 👍

**Pull request merged**
