### PR TITLE
Cookies disabled warning

### PR DESCRIPTION
**Pull request by ezequielc**
@alex-deaconu please review. Thanks

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc looks good. Can you also remove this service and references to it: 
https://github.com/Rise-Vision/common-header/blob/master/src/js/svc-localstorage.js
It doesn't seem to be used anywhere - since there's a similar service provided by AngularJS. 

Thanks.

**Comment by ezequielc** [comment]
Sure @alex-deaconu , I will remove it.

**Comment by ezequielc** [comment]
@alex-deaconu It is being used by https://github.com/Rise-Vision/common-header/blob/master/src/js/svc-userstate.js

**Comment by alex-deaconu** [comment]
@ezequielc yes it is. And by a couple of other services. But like I said, `localStorageService` is an Angular service, so our own implementation of it never runs. Can you double check that's true and see if our version can be removed? Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu I removed the references from userState and common-header directive. I didn't find any other references. Please review. Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc looks good. @olegrise any concerns with the above? Thanks.

**Comment by olegrise** [comment]
@alex-deaconu @ezequielc looks good. I double checked the Store code - I can't find any references to the `localStorageService`.

**Pull request merged**
