### PR TITLE
Feature/update ind trials

### PR DESCRIPTION
**Pull request by RV-Adrian**

### CODE REVIEW

**Comment by RV-Adrian** [comment]
@ghislaineguerin Please review! 
This is a common-header update to support the 'Remove Individual Product Trials' wireframe, staged at https://apps-stage-4.risevision.com/ 
(select Plans Popup)

image

The class addition is not ideal, but I think works while we are deciding on a better solution to get Plans descriptions into Apps.

**Comment by RV-Adrian** [comment]
@fjvallarino 👍

**Comment by ghislaineguerin** [comment]
@RV-Adrian All looks good, but I think we'll have reusability issues with the pseudo-content. Can we change that?

**Comment by RV-Adrian** [comment]
@ghislaineguerin I was wondering about that as well. When it hits development I will work with devs to see other options via Angular. Thx!

**Pull request closed without merging**
